### ISSUE TITLE
去年注册了一个，上传了很多文件，后来发现访问不了了。微软客服让我去找管理员，管理员说账号被微软BAN，我去找谁？？？

### ISSUE THREAD

**Issue by metalbug** [KusakabeShi/free365#38]

**Comment by KusakabeShi** [comment]
你問我，我也不知道呀  

我也說得很清楚啦  
注意:此处取得之所有帐号，皆违反微软ToS。微软有权随时停用，**切勿存留重要资料于其中**  
Noitce: All accounts here are violate Microsoft's Tos, **you may get banned at anytime**.
![image](https://user-images.githubusercontent.com/73118488/167373083-9b5c306e-763e-4f77-a445-77dbf0b41978.png)

就我所知，只有管理員有資格代表全局  
所以正確流程是**微軟封禁了全局，全局管理員向微軟提出異議**  
你不是全局所有者，沒有這個資格了  
合規學校全局有網管會負責這些事務  
而這些全局不合規，管理員也變不出合法學校資料。
開這些白嫖帳號給大家玩玩，也不賺錢。就不願意花費這個心力幫你去討了  

如果這些資料對你真的很重要，唯一的希望就是和管理要到全局管理的帳號密碼，代替原本的全局管理員去和微軟談判  
你可能還要變出合規的學校資料，微軟才有機會給過。不過希望渺茫吧
