### ISSUE TITLE
https://a1_sc.a1od.workers.dev spo为0了

### ISSUE THREAD

**Issue by gsxbxsg** [KusakabeShi/free365#45]

**Comment by gsxbxsg** [comment]
https://a1_free365.a1od.workers.dev/ 也是

**Comment by KusakabeShi** [comment]
恩恩，我有標記喔
OD那個欄位是 X 而不是1TB

現在的教育白嫖潮也逐漸過去了呢，如同我們的青春
當初大家掃域名，撸全局的光景，也變成懷念的時光了...

不過我還是會繼續維護這個列表，只是不會主動去蒐集資訊了
有人提交，我有空就去檢查+merge
